### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Valk2008** [Jim-Kroovy/Mr-Mannequins-Tools#1]
Hello! I`m even cant load start rig.  Its showing this error window
![2019-10-25_11-27-01](https://user-images.githubusercontent.com/53751739/67557518-ecc5a980-f71d-11e9-901b-5177e51471bd.jpg)

Addin # coding: utf8 in begining of file dont helps.

**Comment by Jim-Kroovy** [comment]
I'm not having this issue and you are the first to report it! I'll do my best to fix it, there was a bug with a rigging option so i need to re-upload a bit later anyway. What operating system are you using?

I honestly thought i'd fixed all the utf-8 errors in the previous release.

**Comment by Valk2008** [comment]
Thank you. Yeah I tried Gumroad version first. Using Win 10 x64. 
It`s possible that the problem is on my side, but who knows. Clear is that my knowledge in Python debugging is obviously less than yours )))

**Comment by Jim-Kroovy** [comment]
Alrighty, i'll throw some checks in and get started on fixing this, also what language is your computer using? All sorts of things can cause utf-8 errors, they can be total pain.
 I'll try and find a Python function for reading the file paths that de-codes utf-8 i think i can remember reading about one in the Blender API.

**Comment by Valk2008** [comment]
Language is Russian. I checked all the ways and all of them in English. 
Trying method: 
import sys
reload(sys)
sys.setdefaultencoding('utf8')

Still no. So, I must cling to you

**Comment by Jim-Kroovy** [comment]
Honestly i can't replicate this issue so it could be tough to fix, but i'll keep trying! What i know about utf-8 is that if you have any special characters in the string it can pop an error like that, so if there's anything like umlauts (ä or ö) etc in the file path the add-on is calling that could be causing the error.

**Comment by Valk2008** [comment]
Ok, thanks. It`ll be my own challenge to learn Blender API and Python to fix it for me )))

**Comment by Jim-Kroovy** [comment]
changed the line that caused the error to the bpy.path.display_name_from_filepath(name) method. It made no difference on my end, let me know if it fixes it for you!

I expect that you will either still get the same error or it will throw an error on a different line.

What's particularly odd is that in the functions before your error the same piece of code gets applied to the mesh and material paths. (i change those as well just in case)

**Comment by Valk2008** [comment]
Thank your fast reaction and updates ) So, first time problem has been changed:
![1](https://user-images.githubusercontent.com/53751739/67580126-74c3a780-f74e-11e9-8cd6-ffec6ab74a62.png)
And after reloading Blender the old one returned
![2](https://user-images.githubusercontent.com/53751739/67580209-9e7cce80-f74e-11e9-9cce-f3cbc803634c.png)

So, its obviously my system glitch. The main thing that other users are satisfied.

**Comment by Jim-Kroovy** [comment]
One of my followers has a friend with the same issue! It's because they have an accent over the a in their name ( à )  so it's probably due to your name having special characters after "C:\Users\" i'll continue searching for a fix but i'm not sure how long it might take.

**Comment by Valk2008** [comment]
Thanks, I`ll try it. By the way, do you know about yesterday`s Unreal Live broadcast where the guy admired your addon ))) My congrats
