### ISSUE TITLE
LFS bandwidth exceeded when trying to clone repo

### ISSUE THREAD

**Issue by clifton** [Jim-Kroovy/Mr-Mannequins-Tools#13]
😢 

```
Downloading ARMATURE_UE4_Mannequin_Template.blend (332 KB)
Error downloading object: ARMATURE_UE4_Mannequin_Template.blend (c28690d): Smudge error: Error downloading ARMATURE_UE4_Mannequin_Template.blend (c28690d3862c75fe6214f480d7bf776ab39ceec8bec68a5ee77db24137a83117): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by Jim-Kroovy** [comment]
Yeah all the .blends are stored as git-lfs, this makes sense from an uploading point of view but i didn't realise there was a download limit and that many people would want to be cloning the repo 😢 

I'll look into throwing some money at Github to increase the limit next year.

In the mean time you can download the current stable version from Gumroad and if i update the code it would be possible to just download the scripts from here to replace them

**Comment by clifton** [comment]
no problem. thanks for the work on the plugin!

**Comment by Ruekompa** [comment]
Yes. GitHub LFS is too limited. I encountered the same thing with a
project.

**Comment by Jim-Kroovy** [comment]
Right now i've ripped out the stash folder from my local github folder and it STILL won't let me push it because of the limit...

**Comment by Ruekompa** [comment]
Let us all find a solution to this problem. Necessity is the mother of
invention. Git LFS is open source. So...
