### ISSUE TITLE
blender 2.18 click rig error

### ISSUE THREAD

**Issue by hqztc** [Jim-Kroovy/Mr-Mannequins-Tools#14]
When I click load rig ,that's error   file "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\Mr-Mannequins-Tools-master\_init_.py",line 1303, in execute with bpy.data.libraries.load(MMT.L_rigs,link=false) as (data_from,data_to)
OSError：load C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\Mr-Mannequins-Tools-master\MMT_Stash\ARMATURE_UE4_Mannequin_Skeleton.blend failed to open blend file

**Comment by Jim-Kroovy** [comment]
The blend file has not downloaded, this is either because you didn't read and follow the Github installation instructions or because the monthly quota of Git-lfs bandwidth has been used 😜 this is becoming such a common problem people come to me about that i'm considering deleting the Github repo altogether!

**Comment by hqztc** [comment]
oh,I saw it. thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jim Kroovy"<notifications@github.com&gt;; 
发送时间: 2020年1月3日(星期五) 下午4:16
收件人: "Jim-Kroovy/Mr-Mannequins-Tools"<Mr-Mannequins-Tools@noreply.github.com&gt;; 
抄送: "萌小蛋"<623941106@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Jim-Kroovy/Mr-Mannequins-Tools] blender 2.18 click rig error (#14)




The blend file has not downloaded, this is either because you didn't read and follow the Github installation instructions or because the monthly quota of Git-lfs bandwidth has been used  this is becoming such a common problem people come to me about that i'm considering deleting the Github repo altogether!

**Comment by Jim-Kroovy** [comment]
You're welcome, i'll close the issue and maybe make some changes to the repo to better highlight how to install it from here 👍
