### ISSUE TITLE
Can't load rig - no stash

### ISSUE THREAD

**Issue by malcolmcdixon** [Jim-Kroovy/Mr-Mannequins-Tools#15]
Can't even get this to load a rig. Downloaded zip from Github, read instructions about blend files so downloaded individually. Nothing mentioned in instructions about this problem and how to deal with it. I assume a stash needs to be added but this fails when I enter the path to the MMT_Stash folder. I'm sure that I'm doing something fundamentally incorrect here but it's not a great experience just trying to get the addon to work.

Here's the error:
Traceback (most recent call last):
  File "C:\Users\malco\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\Mr-Mannequins-Tools-master\__init__.py", line 1095, in execute
    prefs = context.preferences.addons["MrMannequinsTools"].preferences
KeyError: 'bpy_prop_collection[key]: key "MrMannequinsTools" not found'

location: <unknown location>:-1

I'm using Blender 2.81.

Any advice appreciated on evaluating this tool. Thanks.

**Comment by malcolmcdixon** [comment]
Sorry, meant to add the error:
Traceback (most recent call last):
  File "C:\Users\malco\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\Mr-Mannequins-Tools-master\__init__.py", line 1095, in execute
    prefs = context.preferences.addons["MrMannequinsTools"].preferences
KeyError: 'bpy_prop_collection[key]: key "MrMannequinsTools" not found'

location: <unknown location>:-1

**Comment by Jim-Kroovy** [comment]
I was about to tell you to just head to Gumroad and download from there, but that error is not the usual error that people get from Github downloading, give me 10 mins... 👍

**Comment by Jim-Kroovy** [comment]
KeyError: 'bpy_prop_collection[key]: key "MrMannequinsTools" not found' means it's not finding the add-ons preferences which is really weird!

**Comment by malcolmcdixon** [comment]
Thanks for the quick reply Jim. I had v1.1 installed first but never used it. I've just watched the stream from last October where your addon was mentioned so removed the old version and installed version 1.2 to try it out. I've only used Blender for a few months and UE4 for about 5 weeks so I'm a newbie but fairly savvy.

**Comment by Jim-Kroovy** [comment]
There's actually quite a lot of things that can go wrong just installing Blender add-ons. I did bit of a search online for you and found this [https://blender.stackexchange.com/questions/63504/addon-preferences-dont-show-consistently](url)

I would suggest downloading from Gumroad (just offer 0) as i think the add-on can't find itself as the installation from Github might be giving it the wrong folder name, or something like that anyway

**Comment by malcolmcdixon** [comment]
Okay thanks, I'll try that appreciate your time.

**Comment by malcolmcdixon** [comment]
Luckily, I know a little bit about Python and programming, so I added the code into __init__.py from step #2 mentioned in the article you linked but it still fails on the same line of code. I will try and download from the other site you mentioned and let you know if that works.

**Comment by drichardson** [comment]
@malcolmcdixon Would you run the following command in CMD or PowerShell and paste the results?

```
dir "C:\Users\malco\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons"
```

**Comment by malcolmcdixon** [comment]
Sorry, but I have removed the addon and reinstalled from Gumroad and it's working. Also, as suspected I wasn't understanding what the stash folder was used for (still don't know) but at least I can load the rig and mesh now.
If it will help though I can redo what I did with the Github download and send the directory listing to you then?

**Comment by drichardson** [comment]
@malcolmcdixon  Yes, if you don't mind. It may help us improve the installation instructions so people don't run into the same problem you did.

**Comment by malcolmcdixon** [comment]
@drichardson Hi Doug, during reinstalling I noticed that the method I'm using to download the .blend files (right-click save as) is probably the issue as the ARMATURE_UE4_Mannequin_Template.blend file is only 93KB and not 324KB as the Gumroad download. So, I guess there's no need to continue downloading these incorrectly just to give a directory listing that will highlight this.

**Comment by drichardson** [comment]
Would you attached one of the files that is smaller than it should be like ARMATURE_UE4_Mannequin_Template.blend?

**Comment by malcolmcdixon** [comment]
[ARMATURE_UE4_Mannequin_Template.zip](https://github.com/Jim-Kroovy/Mr-Mannequins-Tools/files/4047238/ARMATURE_UE4_Mannequin_Template.zip)

Here you go, had to zip it though.

**Comment by drichardson** [comment]
OK, that's what I thought. It's an HTML file, not a .blend file. Whatever link you right clicked > Save As on was actually a link to a webpage that probably then initiated the download, it was not a link directly to the blender file.

@Jim-Kroovy Maybe tell people not to right click download on the Gumroad files. Just regular click them.

**Comment by drichardson** [comment]
Actually, it looks like the right click, Save As was done on a github file.

**Comment by drichardson** [comment]
@malcolmcdixon What did you right click, Save as, on, exactly?

**Comment by malcolmcdixon** [comment]
![image](https://user-images.githubusercontent.com/56974882/72178117-19fb2d00-33da-11ea-8616-bdb727dbfdbb.png)

**Comment by malcolmcdixon** [comment]
Sorry for delay, unexpected family visitors.
![image](https://user-images.githubusercontent.com/56974882/72180680-8d536d80-33df-11ea-964c-3e7cbbcafc62.png)

**Comment by drichardson** [comment]
Ah yes. If you left click on the link you'll see that the result is a webpage and not a blender file download (which is confusing because github uses a link that ends in .blend for the URL).

**Comment by malcolmcdixon** [comment]
Doh, yeah just realised that

**Comment by malcolmcdixon** [comment]
Is there a way to download the .blend files properly from Github then?

**Comment by drichardson** [comment]
Only 1 reliable way:

Go to the [Releases tab](https://github.com/Jim-Kroovy/Mr-Mannequins-Tools/releases) and download a zip file.

However, the latest released version on github is 1.1, so probably not what you want.

The other unreliable way is to use git to clone the repository, but if you aren't familiar with git don't bother, because it might not work (this repository keeps hitting an download bandwidth limit).

It's best to just download them like @Jim-Kroovy said from Gumroad. We probably ought to take the blend files off github entirely. It was my idea to begin with, and it's been nothing but woe and sorrow.

**Comment by malcolmcdixon** [comment]
Hi, that's how I obtained v1.1 but never used it so can't confirm whether that worked or not. I'll try the clone method out of curiosity. I'd never heard of Gumroad but everyone knows Github, so I understand why you'd want it on this platform.

**Comment by drichardson** [comment]
@malcolmcdixon Yes, this is the unreliable nature of using github I mentioned. If you happened to clone at the beginning of the month before the quota has been exceeded, it will work. Otherwise it will fail with the error you are seeing.

**Comment by malcolmcdixon** [comment]
Maybe you should redirect people to the Gumroad download or get 1.2 on the Releases tab. Thanks for the great tool, I hope I find a use for it, I need to watch Jim's videos now.
