### ISSUE TITLE
Question: transfer animation between rig and keep editable?

### ISSUE THREAD

**Issue by pcaben** [Jim-Kroovy/Mr-Mannequins-Tools#16]
Hi, I created my own rig do some animation before, but my rig still got some problem and bone roll issue so I can not directly share the animation unless use retargeting in UE4.

So, Its there any method to retarget the animation from my old rig to the new UE4 rig when the IK structure is different and keep the same amount keyframe for later adjustment not bake all frame?

**Comment by Jim-Kroovy** [comment]
It is possible if you use a whole bunch of Python code, although most people in Blender will tell you it's an almost impossible thing to do. 

In the next update i have a Blender side animation re-targeting system coming, it is a very complex thing to even attempt to do though so it isn't perfect but it does quite a good job most of the time.

This isn't really an issue with my add-on it's an issue with rigging/animation in general, so i'm closing this 👍
