### ISSUE TITLE
Mannequin model is not loaded

### ISSUE THREAD

**Issue by spaksa** [Jim-Kroovy/Mr-Mannequins-Tools#18]
Not sure if this is the right place for this kind of issue, but after installing the add-on in Blender and clicking "Load Rig" in a new project, it only loads the skeleton but no mannequin model/materials/etc. Am I missing something?

![https://i.ibb.co/QkpFbZ1/no-mannequin.png](https://i.ibb.co/QkpFbZ1/no-mannequin.png)

**Comment by Jim-Kroovy** [comment]
Select the rig in object mode then underneath the load rig box a load mesh box should appear.

**Comment by spaksa** [comment]
Oh wow. That works. Thank you! Amazing addon btw.
