### ISSUE TITLE
Animation Import: IK Chain Control Bone Issue

### ISSUE THREAD

**Issue by Hex6168** [Jim-Kroovy/Mr-Mannequins-Tools#19]
Win 8.1
Blender 2.83.4
Mr Mannequins 1.3

When importing animations with applied transformations:
1. IK Control bones remain in their default positions. 
2. Muting their constraints results in the animation running correctly, but breaks the functionality of translate transformations to the IK Chain control bones. 
3(a). Unmuting constraints restores translation functionality, but does not apply the current control bone rotation to the relevant parts of the skeleton and mesh.
3(b). This also has the side effect of breaking the imported animation by the created desynchronization of the control bone to its normal position+rotation relative to the skeleton/mesh.

**Comment by Jim-Kroovy** [comment]
Many people complain about this, it is not fundamentally possible to generate the IK to work with an already baked FBX, the only workaround at the moment is to set the IK vs FK to "Switchable" before importing, which will result in the IK being keyed every frame. I am working on something else that might fix this problem though, time will tell.

**Comment by Hex6168** [comment]
Thanks for the incredibly fast response. I'll look into that as a workaround for now. Thanks for the amazing plug-in you've put together!

**Comment by Jim-Kroovy** [comment]
Closed for update 1.4.0, let see if that fixes it 👍
