### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by brothermechanic** [Jim-Kroovy/Mr-Mannequins-Tools#2]
Hello
Want to trry your script but get issue
![Screenshot_20191030_1572385123](https://user-images.githubusercontent.com/3109995/67811418-c604cb80-faad-11e9-88f7-fc6bce272ff5.jpg)
```
Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/mr-mannequins-tools/__init__.py", line 1020, in execute
    with bpy.data.libraries.load(MMT.L_rigs, link=False, relative=False) as (data_from, data_to):
OSError: load:  failed to open blend file

location: <unknown location>:-1
```
Please help me to fix it.

**Comment by Jim-Kroovy** [comment]
Please read the read me ;) You need to download the add-on from gumroad for the armatures and meshes to be available, the github repository is only the Python, you have a folder missing that the add-on needs to work. I'm unsure about uploading the armature, mesh and material files here so yeah. Go download it from gumroad and it should work. : )

**Comment by brothermechanic** [comment]
Ok
ps: why you dont add MMT_Stash folder on github repo?

**Comment by Jim-Kroovy** [comment]
A couple of reasons, but mostly because i need to find out what licence they would have.

**Comment by brothermechanic** [comment]
but otherwise everything works!
thank you
