### ISSUE TITLE
File Shutdowns on Load Rig - Blender 2.9

### ISSUE THREAD

**Issue by wackjee** [Jim-Kroovy/Mr-Mannequins-Tools#20]
* using blender 2.9*

If I load the UE4 mannequin rig with the add-on and if the first thing that I do is press ctr + z, my whole blender file closes. The issue does not show up if I do other actions first.

**Comment by Jim-Kroovy** [comment]
I never got the email about this issue apologies, but... Closed for update 1.4.0, let see if that fixes it 👍
