### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AlloteSoftware** [Jim-Kroovy/Mr-Mannequins-Tools#21]
FBX export error.
![export_error](https://user-images.githubusercontent.com/45884729/119130331-be669800-ba40-11eb-8383-2705c72755b9.jpg)

![export_error2](https://user-images.githubusercontent.com/45884729/119131257-e60a3000-ba41-11eb-93c5-17421887e012.jpg)

**Comment by Jim-Kroovy** [comment]
This is not actually a bug with the add-on, Blenders FBX export doesn't seem to like special characters when creating the .fbx file. 

Change the name of the "root|Unreal Take|Base Layer" animation to not include any special characters.

**Comment by AlloteSoftware** [comment]
Thank you. Will try.
