### ISSUE TITLE
Importing Animation with .fbx in lowercase

### ISSUE THREAD

**Issue by gtnardy** [Jim-Kroovy/Mr-Mannequins-Tools#3]
Hello! This tool is amazing!

I've figured out an issue related to import of Animations
![image](https://user-images.githubusercontent.com/6226807/68071342-7a297f00-fd58-11e9-8bcc-f1ee8f0921b1.png)

It won't identify and import files named as "*.fbx" in lowercase, only in uppercase.

**Comment by Jim-Kroovy** [comment]
I'm aware of this and have already fixed it ready for the next update thank you though!

The current builds are only made available to my patrons on Patreon for testing until everything is ready for the next update.

**Comment by gtnardy** [comment]
oh great, I was about to commit a pull request for that ;)
https://github.com/gtnardy/Mr-Mannequins-Tools/commit/9e5699bf9da18e6cefee5d656c96849dc3e258fe

**Comment by Jim-Kroovy** [comment]
One thing i haven't had time to figure out is why... if i load a new .blend, load the mannequin rig, then without re-selecting the rig i hit load on the default mesh it crashes Blender... if you feel like trying to replicate that : )

**Comment by gtnardy** [comment]
hm I couldn't follow your steps because to be able to Load the Mesh I need to select the Rig...
I tried creating a new .blend, then Load Rig, but to be able to Load Mesh I need to select the rig, otherwise the button won't appear.
No crashes on this ^

**Comment by Jim-Kroovy** [comment]
Oh fair enough, i wonder why it lets me do it then haha
