### ISSUE TITLE
Add-On with Blender 3.0 

### ISSUE THREAD

**Issue by bisechen** [Jim-Kroovy/Mr-Mannequins-Tools#34]
**What did you break?**
This add-on uses Shift+A to add the Mr Mannequins template in Blender 3.0 alpha, an error message will appear.

**How did you break it?**
with Blender 3.0 alpha add Mr Mannequins template

**Screenshots**
![image](https://i.imgur.com/wSa0tfp.png)

**Additional context**
No

**Comment by Jim-Kroovy** [comment]
First off thank you for using Github to post the issue! Most people just DM me on social media and it's much easier to run support here.

Looks like Blender 3.0 is changing the API for custom bone shapes, until 3.0 is the official stable release i can't fix this or it will break with 2.93. But i can sort this out the moment 3.0 becomes the stable release.

I bet they make some other changes too so it would be useful if you (or anyone else) finds any further bugs with 3.0 you just stick them in this thread so i know where to look in a few months time.

**Comment by bisechen** [comment]
I will test again after Blender 3.0 is released.
Thank you very much for creating such a great Blender ADD-ON.

Wishing you great success in everything you do! All the best!
