### ISSUE TITLE
Problem with loading the add-on

### ISSUE THREAD

**Issue by AgkshayanC** [Jim-Kroovy/Mr-Mannequins-Tools#38]
I installed the tool exactly the way it should be done. And I also enabled it. But the problem is the add-on isn't showing up. I really need. Someone please help me.

**Comment by Jim-Kroovy** [comment]
Many people seem to not realise that the add-on does not appear in the 3D view toolbar (aka N panel).

You can find the export and import settings where they belong with the other import export operators and the armature properties are where they belong in the armature data properties panel.

The only other reason the add-on might not load would be Blender version issues, i only work in the most recent stable release.

Hope that helps a bit! 👍

**Comment by AgkshayanC** [comment]
Thanks for the help. It worked. @Jim-Kroovy

**Comment by Jim-Kroovy** [comment]
No worries, glad you got it sorted.
