### ISSUE TITLE
Blender 3.0 error when adding a mannequin

### ISSUE THREAD

**Issue by Odey555** [Jim-Kroovy/Mr-Mannequins-Tools#40]
Get this error when adding a mannequin template. 
v1.4.10

**Expected behaviour**
Should be able to add mannequins with zero issues. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1361563/148627485-5f85b20b-91b0-4aab-bf6d-47211dea287c.png)

**Comment by Jim-Kroovy** [comment]
This is a known issue with Blender 3.0 changing the API for custom bone shapes, i've fixed it on my end just fixing a few other things before pushing a patch 👍 (Check the 3.0 update issue)
