### ISSUE TITLE
Exporting Animation with Current Frame at 1 breaks animation

### ISSUE THREAD

**Issue by gtnardy** [Jim-Kroovy/Mr-Mannequins-Tools#5]
Hey there, it's me again!

I have noticed another bug related to exporting animations while I have the cursor (current frame) at 1 when exporting animations, here's a video showing up that: https://imgur.com/a/HGlLvYz

Thanks a lot for the tool! Being very useful :)

**Comment by gtnardy** [comment]
it happens if you put the Current Frame on the last frame as well

**Comment by Jim-Kroovy** [comment]
That would be a good example of the difference between > and >= my bad, easy mistake to make. Thanks for noticing! I've just fixed it on my current build and i'll try and squeeze it into a hotfix ASAP

MMT_Export_FBX.py - line 80

"if bpy.context.scene.frame_current > action.frame_range[0] and bpy.context.scene.frame_current < action.frame_range[1]:" 

This condition should be >= and <=  not > and < ... *facepalm* for now if you set the current frame to 0 before exporting it should work fine

**Comment by gtnardy** [comment]
Great that you found it! I'm happy to help

**Comment by Jim-Kroovy** [comment]
I changed that line to be...

"if (bpy.context.scene.frame_current > action.frame_range[0] and bpy.context.scene.frame_current < action.frame_range[1]) or (bpy.context.scene.frame_current == action.frame_range[0] or bpy.context.scene.frame_current == action.frame_range[1]):"

so if you feel like that condition on changing line 80 in MMT_Export_FBX.py before i get the fix uploaded that should work

**Comment by gtnardy** [comment]
hm whats the point of stopping the current frame from getting keyed as the rest pose on export?

**Comment by Jim-Kroovy** [comment]
You get the issue you had once it's imported, whatever current frame you export on becomes the rest pose in the animation, so the current frame needs to be outside of the animations frame range so it doesn't get included : )
