### ISSUE TITLE
Utf-8 decoding error - When a user has an add-on directory with special characters

### ISSUE THREAD

**Issue by Jim-Kroovy** [Jim-Kroovy/Mr-Mannequins-Tools#8]
This is an issue a fair few people who do not have English names have come to me about and i have no idea how to fix it and i have tried a few different things. I'm hoping someone better versed in Python might be able to help out here.

Utf-8 error when loading from default stashes: (Unsolved!) So... Installing the add-on on a user of your computer with a special character in the name (eg: à) will cause a utf-8 de-coding error if you try to load any of the default armatures/meshes/materials. I am unsure how to fix this as the add-on requires the file path to the add-ons installation folder which is, by default on windows, in "C:\Users\[InsertName]\AppData\Roaming\Blender Foundation\Blender\[InsertVersion]\scripts\addons\MrMannequinsTools"

The workarounds users have found: Changing the Blender add-ons directory in the preferences and create/use a different user on your PC that does not have any special characters in it's name)

**Comment by drichardson** [comment]
I setup a test account with Chinese characters in the name, and was able to reproduce the problem. O investigated, but I am still not sure what the exact issue is. Here's what I discovered.

I noticed unusual EnumProperty identifiers are being used. These identifiers are actually paths to the files they identify. This makes perfect sense from an identification point of view, but is outside of the Blender EnumProperty conventions.

For example, the EnumProperty associated with this error is L_Rig, which is are unusual as far as Blender is concerned. The documentation and source I've read on EnumProperty item IDs indicates they should consist only of uppercase letters and underscores.

For example, the EnumProperty associated with this error is L_Rig, which uses full paths to files as enum property item identifiers:

https://github.com/Jim-Kroovy/Mr-Mannequins-Tools/blob/c2e5c7ba806276ca8b1d15bfc50629661940d463/__init__.py#L300-L305

From Blender [RNA_Types.h](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/HEAD:/source/blender/makesrna/RNA_types.h#l409):

```c

/**
 * This struct is are typically defined in arrays which define an *enum* for RNA,
 * which is used by the RNA API both for user-interface and the Python API.
 */
typedef struct EnumPropertyItem {
  /** The internal value of the enum, not exposed to users. */
  int value;
  /**
   * Note that identifiers must be unique within the array,
   * by convention they're upper case with underscores for separators.
   * - An empty string is used to define menu separators.
   * - NULL denotes the end of the array of items.
   */
  const char *identifier;
  /** Optional icon, typically 'ICON_NONE' */
  int icon;
  /** Name displayed in the interface. */
  const char *name;
  /** Longer description used in the interface. */
  const char *description;
} EnumPropertyItem;
```

Additionally, Blender's [RNA architecture wiki](https://wiki.blender.org/wiki/Source/Architecture/RNA) says the following of Enum Items:

> ## Enum Items
> 
>     identifier: use UPPER_CASE with underscores.
>     name: use capital letters with spaces, for example "Conformal", "Angle Based".

What I do not know is if these are just conventions as the documentation states, or if some Blender code actually relies on these conventions.

**Comment by drichardson** [comment]
@Jim-Kroovy It seems like the rig picker should just be a file picker instead of an enum, since that's essentially what it is. Was the primary motivation behind using an enum to get the drop down box behavior in the property panel, or is there another consideration I'm missing?

https://github.com/Jim-Kroovy/Mr-Mannequins-Tools/blob/c2e5c7ba806276ca8b1d15bfc50629661940d463/__init__.py#L1185-L1187

**Comment by Jim-Kroovy** [comment]
So the reason they are enums isn't just so they can be dropdowns, though to begin with that's why i made them like that, it's also so they can be dynamic, so if something in the Stash folder changes things will get added and/or removed from the dropdown, it wouldn't just be the rig picker it would be all of them, meshes, materials and stash selection all function like this as well.

Making it a file picker would maybe work it's worth testing it out, but the error usually comes from the loading line of code so i'm not sure if it would work. 

Using a file picker would however make the process of selecting a bit clunky, especially if a user had many of their own saved meshes/materials in a custom stash folder.

**Comment by drichardson** [comment]
I see. Since the enum item IDs are generated from the contents of a single folder, perhaps the enum item ID should just be the filename instead of the full path name. That would mean the armature/mesh path would need to be derived differently since the full path wouldn't be encoded into the ID. I'll test this idea out. @Jim-Kroovy let me know if you foresee any problems with this approach.

**Comment by Jim-Kroovy** [comment]
I tried to do something like that in the first place but i couldn't figure out a way of getting the filepath, from the enum, i've got better Python since i wrote that bit so maybe it would possible to have the enum as just the filename then do an "os.path.join()" to add the stash folder and file name to the add-on path string in the MMT_Props property group...

That might work, as long it's not the loading function that's causing the error.

**Comment by drichardson** [comment]
All I know at this point is that `MMT.L_rigs` is messed up before the call to load the libraries. I thought it might have something to do with invalid EnumProperty item identifiers, but I don't know that for sure. I'll investigate a bit more.

**Comment by Jim-Kroovy** [comment]
I see, you are probably right then, i'll try making a weird folder name then load from it to see if the loading operator has a problem with special characters.

**Comment by Jim-Kroovy** [comment]
I can confirm that the load operator will take the file path with a folder named "!£$%_à" in it so you must be right it kind of has to be the enum

**Comment by drichardson** [comment]
More info from [Blender's Gotchas documentation](https://docs.blender.org/api/current/info_gotcha.html#unicode-problems):

> ## Unicode Problems
>
> Python supports many different encodings so there is nothing stopping you from writing a script in latin1 or iso-8859-15.
>
> See pep-0263
>
> However this complicates matters for Blender’s Python API because .blend files don’t have an explicit encoding.
> 
> To avoid the problem for Python integration and script authors we have decided all strings in blend files must be UTF-8, ASCII compatible.
> 
> This means assigning strings with different encodings to an object names for instance will raise an error.
> 
> Paths are an exception to this rule since we cannot ignore the existence of non UTF-8 paths on users file-system.

**Comment by drichardson** [comment]
BTW, this can be reproduced without creating a new account. Simply rename the addon folder to something like *MràMannequinsTools*.

**Comment by drichardson** [comment]
I spent a lot of time looking at it today to try to figure out the root cause. All I know is that data goes into Blender (in the form of an EnumProperty item identifier) and doesn't come back out the same way. I even built a custom Blender so I could debug it, but the point I was debugging at (where the log statements was at), was too late... the enum item was already screwed up.

### Ways Forward

1. E-mail the Blender devs to get more info, or spend a lot more time debugging Blender itself while running the MrMannequinsTools addon. My guess is that the result of this investigation will be to avoid using unicode characters in EnumProperty item IDs.

2. Rewrite any code that generates EnumProperty item IDs from file paths by only using the base filename for the enum item ID. This would require some logic changes in order to reconstruct the full path when  needed.

3. Run EnumProperty item IDs generated with file paths through a base64 encoder. This will ensure they have no unicode characters. When the path needs to be extracted, base64 decode them.

1 is time consuming, 2 is the best solution, but requires the most code changes, and 3 is gross but easy to do.

**Comment by Jim-Kroovy** [comment]
I think number 2 i'll have a crack it tomorrow, loading directly from this path.... 

> "D:\Blends\Mr Mannequin\!£$%_à\TEST.blend"

 worked and the add-ons location gets saved as a 'DIRPATH' subtype string so it should be okay to just combine the name with the path if... 

> Paths are an exception to this rule since we cannot ignore the existence of non UTF-8 paths on users file-system.

**Comment by drichardson** [comment]
OK sounds good.

To investigate the root cause further and make it easier to communicate the problem to the Blender team, I created a [minimal example of the problem](https://github.com/drichardson/Mr-Mannequins-Tools/tree/minimal-example).

I'm going to ask about it just to confirm it is the problem.

Another interesting note, on Blender master branch (in progress 2.82), a similar problem occurs even if you do not have a path with unusual characters in it.

**Comment by drichardson** [comment]
Another interesting tidbit from the [EnumProperty](https://docs.blender.org/api/current/bpy.props.html?highlight=bpy%20props%20enumproperty#bpy.props.EnumProperty) documentation:

> Warning
> 
> There is a known bug with using a callback, Python must keep a reference to the strings returned by the callback or Blender will misbehave or even crash.
> 

[Here's someone reporting the exact problem we are seeing](https://developer.blender.org/T50426). Blender developer said to keep a reference to the strings like the API docs say.

I'm going to try that right now.

**Comment by drichardson** [comment]
This looks like it is indeed the issue. I'll have a fix to test out shortly. @Jim-Kroovy I hope you haven't done any work on this yet based on our previous discussion, it's unnecessary and won't actually address the underlying problem.

**Comment by Jim-Kroovy** [comment]
Not yet i was planning to have look in the morning (9:30pm here)

So if i understand correctly the issue is with dynamic enums in general then? I might have a look at moving away from that method altogether if it's an issue in 2.82.

It could be possible to move into using 'DIRPATH' strings added to a collection property... or instead of a drop-down menu maybe use a pop-up menu to select what get's loaded when the operator is called? I'm not too sure but we'll get it fixed one way or another : )

**Comment by drichardson** [comment]
Yes, it's an issue with dynamic enums in general. It's a known underlying bug with a known workaround, which I am implementing now. It's slightly gross, but works just fine and is easy to understand once you know what the problem is.

**Comment by drichardson** [comment]
Fix appears to work. I'm now able to work like normal from the account with the username that has the Chinese character in it. The only remaining (possibly related but not sure) issue I see now is a warning that appears from time to time when I load the mesh:

```
Read blend: C:\Users\σ«ë├á\Desktop\untitled.blend
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1476 pyrna_enum_to_py: current value '3' matches no enum in 'JK_MMT_Props', '', 'L_meshes'
M_UE4Man_Body has been loaded from the mesh library, you might need to clean up image references manually
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1476 pyrna_enum_to_py: current value '3' matches no enum in 'JK_MMT_Props', '', 'L_meshes'
M_UE4Man_ChestLogo has been loaded from the mesh library, you might need to clean up image references manually
Read blend: C:\Users\σ«ë├á\Desktop\untitled.blend
```

**Comment by Jim-Kroovy** [comment]
That's an error i was getting from something else, sometimes it was spamming the console window, i think i fixed it i'll check

**Comment by Jim-Kroovy** [comment]
Yeah i'm pretty sure that's an error from a material issue i was having which i solved by adding in a dedicated property to the mesh to define it as a default mesh and auto-load the material, what was happening in the "matches no enum" error is that i was calling the enum when in the wrong context so it wasn't reachable
